// <auto-generated />
using System;
using Common.DataAccess.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Common.DataAccess.EFCore.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210823172841_ShangedStatusType")]
    partial class ShangedStatusType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Entities.DemDgvOlduredi", b =>
                {
                    b.Property<int>("IdSpDm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_SP_DM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Broi")
                        .HasColumnType("int");

                    b.Property<decimal?>("EdCena")
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("Ed_cena");

                    b.Property<short?>("Faza")
                        .HasColumnType("smallint");

                    b.Property<int?>("IdFirmaDm")
                        .HasColumnType("int")
                        .HasColumnName("Id_firma_dm");

                    b.Property<int?>("IdKn")
                        .HasColumnType("int")
                        .HasColumnName("ID_kn");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<string>("StatusDs")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Status_DS")
                        .IsFixedLength(true);

                    b.Property<decimal?>("TotalCena")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Total_cena");

                    b.Property<string>("User")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Vypros")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.HasKey("IdSpDm")
                        .HasName("PK_olduredi_dgv_dm_ID_SP_DM");

                    b.HasIndex("IdFirmaDm");

                    b.ToTable("dem_dgv_olduredi");
                });

            modelBuilder.Entity("Common.Entities.DemDogovor", b =>
                {
                    b.Property<int>("IdFirmaDm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_firma_DM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ADRES");

                    b.Property<DateTime?>("DataRegN")
                        .HasColumnType("date")
                        .HasColumnName("Data_reg_N");

                    b.Property<string>("Eik")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("EIK");

                    b.Property<short?>("Faza")
                        .HasColumnType("smallint");

                    b.Property<string>("ImeMger")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Ime_mger");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("koga");

                    b.Property<string>("Maneger")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<DateTime?>("NachalnaData")
                        .HasColumnType("date")
                        .HasColumnName("Nachalna data");

                    b.Property<string>("NameF")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name_F");

                    b.Property<int?>("NomDgVSudso")
                        .HasColumnType("int")
                        .HasColumnName("Nom_dg_vSUDSO");

                    b.Property<int?>("ObshtSrokGrf")
                        .HasColumnType("int")
                        .HasColumnName("Obsht_Srok_grf");

                    b.Property<decimal?>("ObshtaCenaBezDds")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Obshta_cena(bez DDS)");

                    b.Property<decimal?>("ObshtaCenaSDds")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Obshta_CENA(s DDS)");

                    b.Property<int?>("PorychkaNomer")
                        .HasColumnType("int")
                        .HasColumnName("Porychka_Nomer");

                    b.Property<string>("RegIndex")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Reg_Index");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<string>("StatusDm")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("STATUS_DM")
                        .IsFixedLength(true);

                    b.Property<string>("User")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("user");

                    b.HasKey("IdFirmaDm")
                        .HasName("PK_dgv_za_demontaj_Id_firma_DM");

                    b.ToTable("dem_dogovor");
                });

            modelBuilder.Entity("Common.Entities.DemPorychka", b =>
                {
                    b.Property<int>("Iddm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ARaion")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("A_Raion");

                    b.Property<int?>("BroiU")
                        .HasColumnType("int")
                        .HasColumnName("Broi_U");

                    b.Property<DateTime?>("DoData")
                        .HasColumnType("date")
                        .HasColumnName("DO_data");

                    b.Property<short?>("Faza")
                        .HasColumnType("smallint");

                    b.Property<int?>("IdFirmaDm")
                        .HasColumnType("int")
                        .HasColumnName("Id_firma_dm");

                    b.Property<int?>("IdKn")
                        .HasColumnType("int")
                        .HasColumnName("Id_kn");

                    b.Property<int?>("IdL")
                        .HasColumnType("int")
                        .HasColumnName("id_L");

                    b.Property<int?>("IdSpNet")
                        .HasColumnType("int")
                        .HasColumnName("Id_SP_NET");

                    b.Property<string>("Ident")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDENT");

                    b.Property<string>("Ime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("IME");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("koga");

                    b.Property<int?>("NomerPoredenDm")
                        .HasColumnType("int")
                        .HasColumnName("Nomer_poreden_DM");

                    b.Property<DateTime?>("OtData")
                        .HasColumnType("date")
                        .HasColumnName("OT_Data");

                    b.Property<DateTime?>("StartData")
                        .HasColumnType("date")
                        .HasColumnName("Start_data");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StatusDp")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Status_dp")
                        .IsFixedLength(true);

                    b.Property<string>("UNom")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("U_nom");

                    b.Property<string>("User")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("user");

                    b.Property<string>("Vypros")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("vypros");

                    b.HasKey("Iddm")
                        .HasName("PK_oldporychka_dm_IDDM");

                    b.HasIndex("IdFirmaDm");

                    b.ToTable("dem_porychka");
                });

            modelBuilder.Entity("Common.Entities.DemRajoni", b =>
                {
                    b.Property<int>("IdRec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_rec")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short?>("Faza")
                        .HasColumnType("smallint")
                        .HasColumnName("FAZA");

                    b.Property<int?>("IdFirmaDm")
                        .HasColumnType("int")
                        .HasColumnName("ID_FIRMA_DM");

                    b.Property<string>("Nkod")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("NKOD");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.HasKey("IdRec")
                        .HasName("PK_demontaj_rajoni_ID_rec");

                    b.HasIndex("IdFirmaDm");

                    b.ToTable("dem_rajoni");
                });

            modelBuilder.Entity("Common.Entities.Lica", b =>
                {
                    b.Property<int>("IdL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_L")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ARaion")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("A_Raion");

                    b.Property<string>("Ap")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("AP");

                    b.Property<string>("Blok")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime?>("DataIzdavane")
                        .HasColumnType("date")
                        .HasColumnName("Data_izdavane");

                    b.Property<string>("EMail")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("e_mail");

                    b.Property<string>("Etaj")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("etaj");

                    b.Property<short>("Faza")
                        .HasColumnType("smallint");

                    b.Property<string>("Fime")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Gime")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("GIME");

                    b.Property<int?>("IdPredstavitel")
                        .HasColumnType("int")
                        .HasColumnName("ID_Predstavitel");

                    b.Property<string>("Ident")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDENT");

                    b.Property<string>("Ime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("IME");

                    b.Property<string>("Jk")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("JK");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("koga");

                    b.Property<string>("Kv")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("KV");

                    b.Property<string>("NLk")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("N_LK");

                    b.Property<string>("Nm")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("NM");

                    b.Property<string>("Nomer")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Pime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PIME");

                    b.Property<string>("Pk")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("PK");

                    b.Property<string>("Predstavitel")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<short>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("smallint");

                    b.Property<string>("StatusF")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Status_F");

                    b.Property<string>("StatusL")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("Status_L");

                    b.Property<string>("Tel")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("tel");

                    b.Property<decimal?>("Tochki1")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("Tochki2")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("Tochki3")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("Tochki4")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("Tochki5")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("UNom")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("U_nom");

                    b.Property<string>("Ul")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("UL");

                    b.Property<string>("User")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("user");

                    b.Property<string>("V8")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<string>("VIdent")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("v_ident");

                    b.Property<string>("VLice")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .HasColumnName("v_lice")
                        .IsFixedLength(true);

                    b.Property<string>("Vh")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("vh");

                    b.HasKey("IdL")
                        .HasName("PK_lica_ID_L");

                    b.ToTable("lica");
                });

            modelBuilder.Entity("Common.Entities.LicaDogovor", b =>
                {
                    b.Property<int>("IdDogL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_dog_L")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataRegN")
                        .HasColumnType("date")
                        .HasColumnName("Data_reg_N");

                    b.Property<short?>("Faza")
                        .HasColumnType("smallint");

                    b.Property<int?>("IdL")
                        .HasColumnType("int")
                        .HasColumnName("Id_L");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("koga");

                    b.Property<string>("RegN")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Reg_N");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<string>("StatusDl")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Status_DL")
                        .IsFixedLength(true);

                    b.Property<string>("UNom")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("U_Nom");

                    b.Property<string>("User")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("user");

                    b.HasKey("IdDogL")
                        .HasName("PK_dogovor_lica_Id_dog_L");

                    b.HasIndex("IdL");

                    b.ToTable("lica_dogovor");
                });

            modelBuilder.Entity("Common.Entities.LicaDogovorOlduredi", b =>
                {
                    b.Property<int>("IdOldurediDgl")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_OLDUREDI_DGL")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Broi")
                        .HasColumnType("int");

                    b.Property<int?>("IdKt")
                        .HasColumnType("int")
                        .HasColumnName("Id_KT");

                    b.Property<int?>("IdL")
                        .HasColumnType("int")
                        .HasColumnName("Id_L");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<string>("StatusU")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Status_U")
                        .IsFixedLength(true);

                    b.Property<string>("User")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("user");

                    b.Property<string>("Vypros")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.HasKey("IdOldurediDgl")
                        .HasName("PK_olduredi_dg_l_ID_OLDUREDI_DGL");

                    b.ToTable("lica_dogovor_olduredi");
                });

            modelBuilder.Entity("Common.Entities.LicaDogovorUredi", b =>
                {
                    b.Property<int>("IdUredDg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Ured_DG")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Broi")
                        .HasColumnType("int");

                    b.Property<int?>("IdDogL")
                        .HasColumnType("int")
                        .HasColumnName("ID_DOG_L");

                    b.Property<int?>("IdKt")
                        .HasColumnType("int")
                        .HasColumnName("Id_KT");

                    b.Property<int?>("IdL")
                        .HasColumnType("int")
                        .HasColumnName("Id_L");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<string>("StatusU")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Status_U")
                        .IsFixedLength(true);

                    b.Property<string>("User")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("user");

                    b.Property<string>("Vypros")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.HasKey("IdUredDg")
                        .HasName("PK_uredi_dg_l_Id_Ured_DG");

                    b.HasIndex("IdDogL");

                    b.ToTable("lica_dogovor_uredi");
                });

            modelBuilder.Entity("Common.Entities.LicaDokumenti", b =>
                {
                    b.Property<int>("IdDok")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Dok")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short?>("Faza")
                        .HasColumnType("smallint");

                    b.Property<int?>("IdKn")
                        .HasColumnType("int")
                        .HasColumnName("ID_KN");

                    b.Property<int?>("IdL")
                        .HasColumnType("int")
                        .HasColumnName("Id_L");

                    b.Property<string>("KodDok")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("Kod_Dok");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<string>("StatusDd")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Status_DD")
                        .IsFixedLength(true);

                    b.Property<string>("TextDok")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("Text_Dok");

                    b.Property<string>("UNom")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("U_NOM");

                    b.Property<string>("User")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Vypros")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("IdDok")
                        .HasName("PK_dokumenti_Id_Dok");

                    b.HasIndex("IdL");

                    b.ToTable("lica_dokumenti");
                });

            modelBuilder.Entity("Common.Entities.LicaFormuliar", b =>
                {
                    b.Property<int>("IdFormuliar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_Formuliar")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("AcstDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("Acst_date");

                    b.Property<string>("Acster")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<short>("Faza")
                        .HasColumnType("smallint")
                        .HasColumnName("faza");

                    b.Property<int?>("IdL")
                        .HasColumnType("int")
                        .HasColumnName("Id_L");

                    b.Property<DateTime?>("RegDate")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("Reg_date");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<string>("StatusF")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Status_F")
                        .IsFixedLength(true);

                    b.Property<string>("UNom")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("U_nom");

                    b.HasKey("IdFormuliar")
                        .HasName("PK_formuliar_ID_Formuliar");

                    b.HasIndex("IdL");

                    b.ToTable("lica_formuliar");
                });

            modelBuilder.Entity("Common.Entities.LicaFormuliarDanni", b =>
                {
                    b.Property<int>("IdVyprosnik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Vyprosnik")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Chislo")
                        .HasColumnType("int");

                    b.Property<string>("DaNe")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("DA_NE");

                    b.Property<short?>("Faza")
                        .HasColumnType("smallint")
                        .HasColumnName("faza");

                    b.Property<int?>("IdFormuliar")
                        .HasColumnType("int")
                        .HasColumnName("ID_Formuliar");

                    b.Property<string>("KodN")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("kod_n");

                    b.Property<int?>("NNmnFk")
                        .HasColumnType("int")
                        .HasColumnName("N_NMN_FK");

                    b.Property<string>("Text")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("TextN")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)")
                        .HasColumnName("Text_N");

                    b.Property<string>("UNom")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("u_nom");

                    b.Property<short?>("Ukazatel")
                        .HasColumnType("smallint");

                    b.Property<string>("Vypros")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("IdVyprosnik")
                        .HasName("PK_f_vypr_danni_Id_Vyprosnik");

                    b.HasIndex("IdFormuliar");

                    b.ToTable("lica_formuliar_danni");
                });

            modelBuilder.Entity("Common.Entities.LicaFormuliarUredi", b =>
                {
                    b.Property<int>("IdUredF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_ured_F")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Broi")
                        .HasColumnType("int");

                    b.Property<int?>("IdFormuliar")
                        .HasColumnType("int")
                        .HasColumnName("Id_formuliar");

                    b.Property<int?>("IdKt")
                        .HasColumnType("int")
                        .HasColumnName("Id_KT");

                    b.Property<int?>("IdL")
                        .HasColumnType("int")
                        .HasColumnName("Id_L");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<string>("StatusU")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Status_U")
                        .IsFixedLength(true);

                    b.Property<int?>("User")
                        .HasColumnType("int")
                        .HasColumnName("user");

                    b.Property<string>("Vypros")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("IdUredF")
                        .HasName("PK_uredi_f_Id_ured_F");

                    b.HasIndex("IdFormuliar");

                    b.ToTable("lica_formuliar_uredi");
                });

            modelBuilder.Entity("Common.Entities.MonDgvPodizpylniteli", b =>
                {
                    b.Property<string>("Adres")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ADRES");

                    b.Property<string>("Eik")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("EIK");

                    b.Property<int>("IdFirma")
                        .HasColumnType("int")
                        .HasColumnName("ID_FIRMA");

                    b.Property<int>("IdPodIzp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PodIZP")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImeMger")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Ime_mger");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("koga");

                    b.Property<string>("Maneger")
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("NameF")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name_F");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<string>("StatusDm")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("STATUS_DM")
                        .IsFixedLength(true);

                    b.Property<string>("User")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("user");

                    b.HasIndex("IdFirma");

                    b.ToTable("mon_dgv_podizpylniteli");
                });

            modelBuilder.Entity("Common.Entities.MonDgvUredi", b =>
                {
                    b.Property<int>("IdSpDost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_Sp_dost")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Broi")
                        .HasColumnType("int");

                    b.Property<int?>("BrojOstatyk")
                        .HasColumnType("int")
                        .HasColumnName("Broj_ostatyk");

                    b.Property<decimal?>("CenaOstatyk")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Cena_ostatyk");

                    b.Property<decimal?>("EdCena")
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("Ed_cena");

                    b.Property<short?>("Faza")
                        .HasColumnType("smallint");

                    b.Property<int?>("GMeseci")
                        .HasColumnType("int")
                        .HasColumnName("G_meseci");

                    b.Property<int?>("IdFirma")
                        .HasColumnType("int")
                        .HasColumnName("Id_firma");

                    b.Property<int?>("IdKn")
                        .HasColumnType("int")
                        .HasColumnName("ID_kn");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<string>("StatusDs")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Status_DS")
                        .IsFixedLength(true);

                    b.Property<decimal?>("TotalCena")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Total_cena");

                    b.Property<string>("User")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Vypros")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("IdSpDost")
                        .HasName("PK_uredi_dgv_dost_Id_Sp_dost");

                    b.HasIndex("IdFirma");

                    b.ToTable("mon_dgv_uredi");
                });

            modelBuilder.Entity("Common.Entities.MonDogovor", b =>
                {
                    b.Property<int>("IdFirma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_FIRMA")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ADRES");

                    b.Property<DateTime?>("DataRegN")
                        .HasColumnType("date")
                        .HasColumnName("Data_reg_N");

                    b.Property<string>("Eik")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("EIK");

                    b.Property<short?>("Faza")
                        .HasColumnType("smallint");

                    b.Property<string>("ImeMger")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ime_mger");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("koga");

                    b.Property<string>("Maneger")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("NachalnaData")
                        .HasColumnType("date")
                        .HasColumnName("Nachalna data");

                    b.Property<string>("NameF")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name_F");

                    b.Property<int?>("NomDgVSudso")
                        .HasColumnType("int")
                        .HasColumnName("Nom_dg_vSUDSO");

                    b.Property<int?>("NomerPorychka")
                        .HasColumnType("int")
                        .HasColumnName("Nomer_porychka");

                    b.Property<int?>("ObshtSrokGrf")
                        .HasColumnType("int")
                        .HasColumnName("Obsht_Srok_grf");

                    b.Property<decimal?>("ObshtaCenaBezDds")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Obshta_cena(bez DDS)");

                    b.Property<decimal?>("ObshtaCenaSDds")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("Obshta_CENA(s DDS)");

                    b.Property<string>("RegIndex")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("Reg_Index");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<string>("StatusDm")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("STATUS_DM")
                        .IsFixedLength(true);

                    b.Property<string>("User")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("user");

                    b.HasKey("IdFirma")
                        .HasName("PK_dgv_dostavchici_ID_FIRMA");

                    b.ToTable("mon_dogovor");
                });

            modelBuilder.Entity("Common.Entities.MonGrafik", b =>
                {
                    b.Property<int>("IdGrafik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_GRAFIK")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ARaion")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("A_Raion");

                    b.Property<string>("Ap")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("AP");

                    b.Property<string>("Blok")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("BroiU")
                        .HasColumnType("int")
                        .HasColumnName("Broi_U");

                    b.Property<DateTime?>("DoData")
                        .HasColumnType("date")
                        .HasColumnName("DO_data");

                    b.Property<string>("Etaj")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("etaj");

                    b.Property<short?>("Faza")
                        .HasColumnType("smallint");

                    b.Property<string>("Fime")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Gime")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("GIME");

                    b.Property<int?>("IdFirma")
                        .HasColumnType("int")
                        .HasColumnName("Id_firma");

                    b.Property<int?>("IdKn")
                        .HasColumnType("int")
                        .HasColumnName("Id_kn");

                    b.Property<int?>("IdL")
                        .HasColumnType("int")
                        .HasColumnName("id_L");

                    b.Property<int?>("IdSpNet")
                        .HasColumnType("int")
                        .HasColumnName("Id_SP_NET");

                    b.Property<string>("Ident")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDENT");

                    b.Property<int?>("Idm")
                        .HasColumnType("int")
                        .HasColumnName("IDM");

                    b.Property<string>("Ime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("IME");

                    b.Property<string>("Jk")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("JK");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("koga");

                    b.Property<string>("Kv")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("KV");

                    b.Property<string>("Nm")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("NM");

                    b.Property<string>("Nomer")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("NomerPoredenM")
                        .HasColumnType("int")
                        .HasColumnName("Nomer_poreden_M");

                    b.Property<DateTime?>("OtData")
                        .HasColumnType("date")
                        .HasColumnName("OT_Data");

                    b.Property<string>("Pime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PIME");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StatusDp")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Status_dp")
                        .IsFixedLength(true);

                    b.Property<string>("Tel")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("tel");

                    b.Property<string>("UNom")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("U_nom");

                    b.Property<string>("Ul")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("UL");

                    b.Property<string>("User")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("user");

                    b.Property<string>("Vh")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("vh");

                    b.Property<string>("Vypros")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("vypros");

                    b.HasKey("IdGrafik")
                        .HasName("PK_grafik_m_Id_GRAFIK");

                    b.HasIndex("Idm");

                    b.ToTable("mon_grafik");
                });

            modelBuilder.Entity("Common.Entities.MonOtchet", b =>
                {
                    b.Property<int>("IdOtchet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_OTCHET")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BroiU")
                        .HasColumnType("int")
                        .HasColumnName("Broi_U");

                    b.Property<DateTime?>("DataMontazj")
                        .HasColumnType("datetime")
                        .HasColumnName("data_montazj");

                    b.Property<DateTime?>("DoData")
                        .HasColumnType("date")
                        .HasColumnName("DO_data");

                    b.Property<byte[]>("FabrNomer")
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("fabr_nomer");

                    b.Property<short?>("Faza")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("GarNomer")
                        .HasMaxLength(50)
                        .HasColumnType("varbinary(50)")
                        .HasColumnName("gar_nomer");

                    b.Property<int?>("IdGrafik")
                        .HasColumnType("int")
                        .HasColumnName("Id_GRAFIK");

                    b.Property<int>("Idm")
                        .HasColumnType("int")
                        .HasColumnName("IDM");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("koga");

                    b.Property<DateTime?>("NaData")
                        .HasColumnType("date")
                        .HasColumnName("NA_DATA");

                    b.Property<int>("NomerPoredenM")
                        .HasColumnType("int")
                        .HasColumnName("Nomer_poreden_M");

                    b.Property<DateTime?>("OtData")
                        .HasColumnType("date")
                        .HasColumnName("OT_Data");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StatusDp")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Status_dp")
                        .IsFixedLength(true);

                    b.Property<string>("User")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("user");

                    b.HasKey("IdOtchet")
                        .HasName("PK_otchet_m_ID_OTCHET");

                    b.HasIndex("Idm");

                    b.ToTable("mon_otchet");
                });

            modelBuilder.Entity("Common.Entities.MonPorychka", b =>
                {
                    b.Property<int>("Idm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDM")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ARaion")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("A_Raion");

                    b.Property<int?>("BroiU")
                        .HasColumnType("int")
                        .HasColumnName("Broi_U");

                    b.Property<DateTime?>("DoData")
                        .HasColumnType("date")
                        .HasColumnName("DO_data");

                    b.Property<short?>("Faza")
                        .HasColumnType("smallint");

                    b.Property<int?>("IdFirma")
                        .HasColumnType("int")
                        .HasColumnName("Id_firma");

                    b.Property<int?>("IdKn")
                        .HasColumnType("int")
                        .HasColumnName("Id_kn");

                    b.Property<int?>("IdL")
                        .HasColumnType("int")
                        .HasColumnName("id_L");

                    b.Property<int?>("IdSpNet")
                        .HasColumnType("int")
                        .HasColumnName("Id_SP_NET");

                    b.Property<string>("Ident")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("IDENT");

                    b.Property<string>("Ime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("IME");

                    b.Property<DateTime?>("Koga")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasColumnName("koga");

                    b.Property<int?>("NomerPoredenM")
                        .HasColumnType("int")
                        .HasColumnName("Nomer_poreden_M");

                    b.Property<DateTime?>("OtData")
                        .HasColumnType("date")
                        .HasColumnName("OT_Data");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("Start_date");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("StatusDp")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("Status_dp")
                        .IsFixedLength(true);

                    b.Property<string>("UNom")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("U_nom");

                    b.Property<string>("User")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("user");

                    b.Property<string>("Vypros")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("vypros");

                    b.HasKey("Idm")
                        .HasName("PK_porychka_m_IDM");

                    b.HasIndex("IdFirma");

                    b.HasIndex("IdL");

                    b.ToTable("mon_porychka");
                });

            modelBuilder.Entity("Common.Entities.MonRajoni", b =>
                {
                    b.Property<int>("IdRec")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_rec")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short?>("Faza")
                        .HasColumnType("smallint")
                        .HasColumnName("FAZA");

                    b.Property<int?>("IdFirma")
                        .HasColumnType("int")
                        .HasColumnName("Id_firma");

                    b.Property<string>("Nkod")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("NKOD");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.HasKey("IdRec")
                        .HasName("PK_dostavchik_rajoni_ID_rec");

                    b.HasIndex("IdFirma");

                    b.ToTable("mon_rajoni");
                });

            modelBuilder.Entity("Common.Entities.NJk", b =>
                {
                    b.Property<string>("Nkod")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("nkod");

                    b.Property<string>("KodNmn")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("kod_nmn");

                    b.Property<string>("Nime")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nime");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Nkod")
                        .HasName("PK_n_jk_nkod");

                    b.ToTable("n_jk");
                });

            modelBuilder.Entity("Common.Entities.NKmetstva", b =>
                {
                    b.Property<string>("Nkod")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("nkod");

                    b.Property<string>("Nime")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nime");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Nkod")
                        .HasName("PK_n_kmetstva_nkod");

                    b.ToTable("n_kmetstva");
                });

            modelBuilder.Entity("Common.Entities.NKvartali", b =>
                {
                    b.Property<string>("Nkod")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("nkod");

                    b.Property<string>("KodNmn")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("kod_nmn");

                    b.Property<string>("Nime")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nime");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Nkod")
                        .HasName("PK_n_kvartali_nkod");

                    b.ToTable("n_kvartali");
                });

            modelBuilder.Entity("Common.Entities.NNmnObshti", b =>
                {
                    b.Property<int>("IdKn")
                        .HasColumnType("int")
                        .HasColumnName("id_kn");

                    b.Property<short>("Faza")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("smallint")
                        .IsFixedLength(true);

                    b.Property<string>("KodNmn")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("kod_nmn");

                    b.Property<string>("KodPozicia")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("Kod_pozicia");

                    b.Property<short>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("smallint")
                        .HasColumnName("status")
                        .IsFixedLength(true);

                    b.Property<string>("Text")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Vypros")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("vypros");

                    b.HasKey("IdKn")
                        .HasName("PK_n_nmn_obshti_id_kn");

                    b.ToTable("n_nmn_obshti");
                });

            modelBuilder.Entity("Common.Entities.NNsMestum", b =>
                {
                    b.Property<string>("Nkod")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("nkod");

                    b.Property<string>("Kmetstvo")
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("KodNmn")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("kod_nmn");

                    b.Property<string>("Nime")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("nime");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.HasKey("Nkod")
                        .HasName("PK_n_ns_mesta_nkod");

                    b.ToTable("n_ns_mesta");
                });

            modelBuilder.Entity("Common.Entities.NRaioni", b =>
                {
                    b.Property<string>("KodNmn")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("kod_nmn");

                    b.Property<string>("Nime")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("NIME");

                    b.Property<string>("Nkod")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("NKOD");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<int?>("ZCode")
                        .HasColumnType("int")
                        .HasColumnName("Z_Code");

                    b.ToTable("n_raioni");
                });

            modelBuilder.Entity("Common.Entities.NShablonF", b =>
                {
                    b.Property<int>("IdN")
                        .HasColumnType("int")
                        .HasColumnName("ID_N");

                    b.Property<string>("Faza")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<int?>("Poleta")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<string>("TblVBd")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("TBL_vBD");

                    b.Property<string>("Text")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Vypros")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("IdN")
                        .HasName("PK_shablon_f_ID_N");

                    b.ToTable("n_shablon_f");
                });

            modelBuilder.Entity("Common.Entities.NSpisykNmn", b =>
                {
                    b.Property<string>("KodNmn")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("kod_nmn");

                    b.Property<short>("Faza")
                        .HasColumnType("smallint");

                    b.Property<string>("Ime")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Komentar")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<short>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("smallint")
                        .IsFixedLength(true);

                    b.Property<string>("TablicaVBazata")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Tablica_vBazata");

                    b.Property<string>("Vypros")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.HasKey("KodNmn")
                        .HasName("PK_n_spisyk_nmn_kod_nmn");

                    b.ToTable("n_spisyk_nmn");
                });

            modelBuilder.Entity("Common.Entities.NSpravki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Faza")
                        .HasColumnType("smallint");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Komentar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<short>("Tip")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("n_spravki");
                });

            modelBuilder.Entity("Common.Entities.NStatusi", b =>
                {
                    b.Property<int>("IdSt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id_St")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("Faza")
                        .HasColumnType("smallint");

                    b.Property<string>("KodNmn")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("kod_nmn");

                    b.Property<string>("Komentar")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Rolia")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength(true);

                    b.Property<short>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("smallint")
                        .IsFixedLength(true);

                    b.Property<string>("StatusCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("Status_Code");

                    b.Property<string>("StatusName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Status_name");

                    b.Property<string>("TableName")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("Table_name");

                    b.Property<string>("Text")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdSt")
                        .HasName("PK_n_statusi_Id_St");

                    b.ToTable("n_statusi");
                });

            modelBuilder.Entity("Common.Entities.NUlicii", b =>
                {
                    b.Property<string>("Nkod")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("nkod");

                    b.Property<string>("KodNmn")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("kod_nmn");

                    b.Property<string>("Nime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nime");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("WnasmNkod")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("wnasm_nkod");

                    b.Property<string>("WnuliNkod")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasColumnName("wnuli_nkod");

                    b.HasKey("Nkod")
                        .HasName("PK_n_ulicii_nkod");

                    b.ToTable("n_ulicii");
                });

            modelBuilder.Entity("Common.Entities.Obhvat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Obhvat");
                });

            modelBuilder.Entity("Common.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Common.Entities.Settings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Common.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressCity")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("City");

                    b.Property<double?>("AddressLat")
                        .HasColumnType("float")
                        .HasColumnName("Lat");

                    b.Property<double?>("AddressLng")
                        .HasColumnType("float")
                        .HasColumnName("Lng");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Street");

                    b.Property<string>("AddressZipCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ZipCode");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Common.Entities.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Common.Entities.UserObhvat", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ObhvatId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ObhvatId");

                    b.HasIndex("ObhvatId");

                    b.ToTable("UserObhvat");
                });

            modelBuilder.Entity("Common.Entities.UserPhoto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("UserPhotos");
                });

            modelBuilder.Entity("Common.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Common.Entities.DemDgvOlduredi", b =>
                {
                    b.HasOne("Common.Entities.DemDogovor", "IdFirmaDmNavigation")
                        .WithMany("DemDgvOlduredis")
                        .HasForeignKey("IdFirmaDm")
                        .HasConstraintName("FK_dem_dgv_olduredi_dem_dogovor");

                    b.Navigation("IdFirmaDmNavigation");
                });

            modelBuilder.Entity("Common.Entities.DemPorychka", b =>
                {
                    b.HasOne("Common.Entities.DemDogovor", "IdFirmaDmNavigation")
                        .WithMany("DemPorychkas")
                        .HasForeignKey("IdFirmaDm")
                        .HasConstraintName("FK_dem_oldporychka_dem_dogovor");

                    b.Navigation("IdFirmaDmNavigation");
                });

            modelBuilder.Entity("Common.Entities.DemRajoni", b =>
                {
                    b.HasOne("Common.Entities.DemDogovor", "IdFirmaDmNavigation")
                        .WithMany("DemRajonis")
                        .HasForeignKey("IdFirmaDm")
                        .HasConstraintName("FK_dem_rajoni_dem_dogovor");

                    b.Navigation("IdFirmaDmNavigation");
                });

            modelBuilder.Entity("Common.Entities.LicaDogovor", b =>
                {
                    b.HasOne("Common.Entities.Lica", "IdLNavigation")
                        .WithMany("LicaDogovors")
                        .HasForeignKey("IdL")
                        .HasConstraintName("FK_lica_dogovor_lica");

                    b.Navigation("IdLNavigation");
                });

            modelBuilder.Entity("Common.Entities.LicaDogovorUredi", b =>
                {
                    b.HasOne("Common.Entities.LicaDogovor", "IdDogLNavigation")
                        .WithMany("LicaDogovorUredis")
                        .HasForeignKey("IdDogL")
                        .HasConstraintName("FK_lica_dogovor_uredi_lica_dogovor");

                    b.Navigation("IdDogLNavigation");
                });

            modelBuilder.Entity("Common.Entities.LicaDokumenti", b =>
                {
                    b.HasOne("Common.Entities.Lica", "IdLNavigation")
                        .WithMany("LicaDokumentis")
                        .HasForeignKey("IdL")
                        .HasConstraintName("FK_lica_dokumenti_lica");

                    b.Navigation("IdLNavigation");
                });

            modelBuilder.Entity("Common.Entities.LicaFormuliar", b =>
                {
                    b.HasOne("Common.Entities.Lica", "IdLNavigation")
                        .WithMany("LicaFormuliars")
                        .HasForeignKey("IdL")
                        .HasConstraintName("FK_lica_formuliar_lica");

                    b.Navigation("IdLNavigation");
                });

            modelBuilder.Entity("Common.Entities.LicaFormuliarDanni", b =>
                {
                    b.HasOne("Common.Entities.LicaFormuliar", "IdFormuliarNavigation")
                        .WithMany("LicaFormuliarDannis")
                        .HasForeignKey("IdFormuliar")
                        .HasConstraintName("FK_lica_formuliar_danni_lica_formuliar");

                    b.Navigation("IdFormuliarNavigation");
                });

            modelBuilder.Entity("Common.Entities.LicaFormuliarUredi", b =>
                {
                    b.HasOne("Common.Entities.LicaFormuliar", "IdFormuliarNavigation")
                        .WithMany("LicaFormuliarUredis")
                        .HasForeignKey("IdFormuliar")
                        .HasConstraintName("FK_lica_formuliar_uredi_lica_formuliar");

                    b.Navigation("IdFormuliarNavigation");
                });

            modelBuilder.Entity("Common.Entities.MonDgvPodizpylniteli", b =>
                {
                    b.HasOne("Common.Entities.MonDogovor", "IdFirmaNavigation")
                        .WithMany()
                        .HasForeignKey("IdFirma")
                        .HasConstraintName("FK_mon_dgv_podizpylniteli_mon_dogovor")
                        .IsRequired();

                    b.Navigation("IdFirmaNavigation");
                });

            modelBuilder.Entity("Common.Entities.MonDgvUredi", b =>
                {
                    b.HasOne("Common.Entities.MonDogovor", "IdFirmaNavigation")
                        .WithMany("MonDgvUredis")
                        .HasForeignKey("IdFirma")
                        .HasConstraintName("FK_mon_dgv_uredi_mon_dogovor");

                    b.Navigation("IdFirmaNavigation");
                });

            modelBuilder.Entity("Common.Entities.MonGrafik", b =>
                {
                    b.HasOne("Common.Entities.MonPorychka", "IdmNavigation")
                        .WithMany("MonGrafiks")
                        .HasForeignKey("Idm")
                        .HasConstraintName("FK_mon_grafik_mon_porychka");

                    b.Navigation("IdmNavigation");
                });

            modelBuilder.Entity("Common.Entities.MonOtchet", b =>
                {
                    b.HasOne("Common.Entities.MonPorychka", "IdmNavigation")
                        .WithMany("MonOtchets")
                        .HasForeignKey("Idm")
                        .HasConstraintName("FK_mon_otchet_mon_porychka")
                        .IsRequired();

                    b.Navigation("IdmNavigation");
                });

            modelBuilder.Entity("Common.Entities.MonPorychka", b =>
                {
                    b.HasOne("Common.Entities.MonDogovor", "IdFirmaNavigation")
                        .WithMany("MonPorychkas")
                        .HasForeignKey("IdFirma")
                        .HasConstraintName("FK_mon_porychka_mon_dogovor");

                    b.HasOne("Common.Entities.Lica", "IdLNavigation")
                        .WithMany("MonPorychkas")
                        .HasForeignKey("IdL")
                        .HasConstraintName("FK_mon_porychka_lica");

                    b.Navigation("IdFirmaNavigation");

                    b.Navigation("IdLNavigation");
                });

            modelBuilder.Entity("Common.Entities.MonRajoni", b =>
                {
                    b.HasOne("Common.Entities.MonDogovor", "IdFirmaNavigation")
                        .WithMany("MonRajonis")
                        .HasForeignKey("IdFirma")
                        .HasConstraintName("FK_mon_rajoni_mon_dogovor");

                    b.Navigation("IdFirmaNavigation");
                });

            modelBuilder.Entity("Common.Entities.Settings", b =>
                {
                    b.HasOne("Common.Entities.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("Common.Entities.Settings", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.Entities.UserClaim", b =>
                {
                    b.HasOne("Common.Entities.User", null)
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Entities.UserObhvat", b =>
                {
                    b.HasOne("Common.Entities.Obhvat", "Obhvat")
                        .WithMany("UserObhvat")
                        .HasForeignKey("ObhvatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Entities.User", null)
                        .WithMany("UserObhvat")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Obhvat");
                });

            modelBuilder.Entity("Common.Entities.UserPhoto", b =>
                {
                    b.HasOne("Common.Entities.User", "User")
                        .WithOne("Photo")
                        .HasForeignKey("Common.Entities.UserPhoto", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Common.Entities.UserRole", b =>
                {
                    b.HasOne("Common.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.Entities.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Common.Entities.DemDogovor", b =>
                {
                    b.Navigation("DemDgvOlduredis");

                    b.Navigation("DemPorychkas");

                    b.Navigation("DemRajonis");
                });

            modelBuilder.Entity("Common.Entities.Lica", b =>
                {
                    b.Navigation("LicaDogovors");

                    b.Navigation("LicaDokumentis");

                    b.Navigation("LicaFormuliars");

                    b.Navigation("MonPorychkas");
                });

            modelBuilder.Entity("Common.Entities.LicaDogovor", b =>
                {
                    b.Navigation("LicaDogovorUredis");
                });

            modelBuilder.Entity("Common.Entities.LicaFormuliar", b =>
                {
                    b.Navigation("LicaFormuliarDannis");

                    b.Navigation("LicaFormuliarUredis");
                });

            modelBuilder.Entity("Common.Entities.MonDogovor", b =>
                {
                    b.Navigation("MonDgvUredis");

                    b.Navigation("MonPorychkas");

                    b.Navigation("MonRajonis");
                });

            modelBuilder.Entity("Common.Entities.MonPorychka", b =>
                {
                    b.Navigation("MonGrafiks");

                    b.Navigation("MonOtchets");
                });

            modelBuilder.Entity("Common.Entities.Obhvat", b =>
                {
                    b.Navigation("UserObhvat");
                });

            modelBuilder.Entity("Common.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Common.Entities.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Photo");

                    b.Navigation("Settings");

                    b.Navigation("UserObhvat");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
